@baseUrl=http://localhost:5000/posts

### RITORNA LA LISTA DEI POSTs
GET {{baseUrl}}
###
GET {{baseUrl}}?page=5&perPage=5
### RITORNA IL SINGOLO POST
GET {{baseUrl}}/66ce16474e272b27ab419481

### RITORNA IL PRIMO RISULTATO NELLA RICERCA DEL TITOLO
GET {{baseUrl}}?title=dUe

### CREA UN NUOVO POST
POST {{baseUrl}}
Content-Type: application/json

{
  "category":"prova generale",
    "title":"another one",
    "cover": "url",
    "readTime":500,
    "author":"sasa@gmail.com",
    "content": "ciao"
}
### MODIFICA UN POST CON ID ASSOCIATO
PUT {{baseUrl}}/66ce16474e272b27ab419481
Content-Type: application/json

{
  "author":"Mario Rossi"
}
### CANCELLA UN POST CON ID ASSOCIATO
DELETE {{baseUrl}}/66ce16474e272b27ab419481